name: ElderCare PR Builder
on:
  pull_request:
    branches: [ develop, main ]
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'temurin'
          cache: gradle

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Touch local properties
        run: touch local.properties

      - name: Access Local Properties
        env:
          HFM_BASE_URL: ${{ secrets.BASE_URL }}
        run: echo "base.url=\"$BASE_URL\"" >> local.properties

      - name: Lint Check
        run: ./gradlew ktlintCheck -PcompileSdkVersion=34

      - name: Build with Gradle
        run: ./gradlew build --daemon --parallel
